version: '2'
services:
  wordcounter-app:
    image: wordcounter
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://wordcounter-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=wordCounter
      - JHIPSTER_CACHE_REDIS_SERVER=redis://wordcounter-redis:6379
      - JHIPSTER_CACHE_REDIS_CLUSTER=false
      # - JHIPSTER_CACHE_REDIS_SERVER=redis://wordcounter-redis:6379
      # - JHIPSTER_CACHE_REDIS_CLUSTER=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  wordcounter-mongodb:
    extends:
      file: mongodb.yml
      service: wordcounter-mongodb
  wordcounter-redis:
    extends:
      file: redis.yml
      service: wordcounter-redis
